config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "bikes#top"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :bikes, only: [:new,:index, :show, :create] do
    resources :comments
    collection do
      get :top
      get :search
      get :out, defaults: { format: 'json' }
      patch :report, defaults: { format: 'json' }
      get 'chat', defaults: { format: 'json' }
    end
    # member do 
    #   get :search
    # end
  end
  resources :users
  resources :groups,only:[:new, :index, :create, :show] do
    resources :chats,only:[:index, :create]

    namespace :api do
      resources :chats, only: :index, defaults: { format: 'json' }
    end
  end
  resources :gets,only:[:index, :show] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_many :comments
  has_many :images
  belongs_to :user
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :brand,:weight,:price,:model, presence: true  
  validates :images, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :group,optional: true
  belongs_to :user,optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user,optional: true
  belongs_to :bike,optional: true
end

app/models/danger.rb
class Danger < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :chats
  validates :name, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :bike,optional:true
  # belongs_to :bike
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :bikes
         has_many :comments
         has_many :chats
        #  has_many :groups, through: :users_groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :bike_params, only: [:create]
  before_action :set_seller_user,only: [:out,:first,:report]
  
  def top
    @bikes = Bike.all
    @Brands =Bike.pluck(:brand)
    @brands = Array @Brands.uniq #重複しているブランドを省くため
    @groups = Group.all
    @chats = Chat.all
    @chats5 = Chat.all.order(created_at: "DESC").first(5) #新しい5件のチャット
    @ids = @chats5.pluck(:group_id) #group_idだけの配列を作成
    @groupIds = Array @ids.uniq #group_idが重複しているチャットを排除
  end
  
  def index
    @bikes = Bike.all
  end
  
  def show
    @bike = Bike.find(params[:id])
    @images = @bike.images
    @comments = @bike.comments
    @user = User.find(@bike.user_id)
    if @user.banned == nil
    else
    end
  end
  
  def new
    if current_user.banned != nil
      redirect_to root_path
      flash.now[:alert] = "凍結されています"
    else
      @bike = Bike.new
      @images = @bike.images.new
    end
  end

  def search
    @bikes = Bike.where(brand: params[:format])
    if params[:search].present?
        # @search = Bike.where(model:params[:search])
        @search = Bike.where("model LIKE ?", "%#{params[:search]}%")
    end
  end
  def chat
    @chats = Chat.where(group_id: params[:group_id]).order(id:"DESC").first(4);
  end


  def create
    # binding.pry
    if current_user.banned == nil   #凍結されていると投稿できない
      @bike = Bike.new(bike_params)
      # binding.pry
      if @bike.save
        redirect_to root_path
      elsif params[:bike][:images_attributes] == nil    #画像がなかった場合
        @images = @bike.images.new
        render action: :new
      else    #画像があった場合
        render action: :new
        # redirect_to new_bike_path
      end
    else        
    end
  end

  def out
      @info = 0
  end

  def report   
    @danger = Danger.new(reported: @seller.id, reporter: current_user.id)  #まずはここでdangerテーブルに通報情報を登録する
    if @danger.save
    else
      flash[:失敗]
    end
    @dangers = Danger.all
    @reported = @dangers.where(reported: @seller.id)     #ある人が通報されたもの全て
    @reporter_count = @reported.where(reporter: current_user.id).count   #ある出品者に対してある通報者一人が何回通報したか
    if @seller.reported == nil
      @seller.reported = 0
      @number = @seller.reported + 1.0/@reporter_count  #  1回目0 + 1/1になり@numberが1になる
    else
      @number = @seller.reported + 1.0/@reporter_count    #2回目以降の通報処理
    end
    if @number < 5.0
      @user = User.update(@seller,reported: @number)  #通報ポイントが5未満ならば通報後の通報ポイントをupdateする
      @word = "safe"
    else
      @word ="ban"
      @user = User.update(@seller,reported: 5.0,banned: @seller.id)   #通報ポイントが5を超えるとreportedに5が入りbannedに@sellerのidが入る
    end
  end

  

  private
    def bike_params
      params.require(:bike).permit(:model, :price, :weight,:brand,:reported, images_attributes:[:src]).merge(user_id: current_user.id)
    end

    def set_seller_user
      @seller = User.find(params[:user_id])
    end

    
  end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def new
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_group
  def index
    @chat = Chat.new
    @chats = @group.chats.includes(:user)
  end

  def create
    @chat = @group.chats.new(chat_params)
    # binding.pry
    @user = User.find(@chat.user_id)
    # binding.pry
    if @chat.save
      respond_to do |format|
        format.html {redirect_to group_chats_path(params[:group_id])}
        format.json
      end
    else
      @chats = @group.chats.includes(:user)
      render :index
    end
    # binding.pry
    # if @chat.save
    #   render :index
    # else
    #   render :index
    # end
  end
  private
  def chat_params
    # binding.pry
    params.require(:chat).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_bike
  def index
    @comments = @bike.comments
    # binding.pry
    # @comments = @bike.comments.find(params[:id])
    # binding.pry
  end

  def new
    @comment = @bike.comments.new
  end
  def create
    # binding.pry
    @comment = @bike.comments.create(comment_params)
    # binding.pry
    redirect_to bike_path(params[:bike_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id)
  end
  def set_bike
    @bike = Bike.find(params[:bike_id])
  end
end

app/controllers/gets_controller.rb
class GetsController < ApplicationController
  def index
    @bikes = Bike.all
    # binding.pry
  end

  
    # binding.pry
    # @bikes = Bike.find(params[:format])
    # @form = Bike.find(params[:format])
    # binding.pry


  #   if params[:search].present?
  #     @forms = Bike.where(model:"#{params[:search]}")
  #     # binding.pry
  #   else
  #     @forms = Bike.none
  #   end

  #   @bike = Bike.find(params[:format])
  #   # binding.pry
  #   if params[:format].present?
  #     @bikes = Bike.where(brand:"#{@bike.brand}")
  #     # binding.pry
  #   else
  #     @bikes = Bike.none
  #   end
  #   # binding.pry
  

  def show
    
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end
  
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end
  private
  def group_params
    params.require(:group).permit(:name,user_ids:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @bikes = Bike.where(user_id: current_user.id)
  end

  def edit
    
  end

  def update
    
  end
private
  def user_params
    params.require(:user).permit(:name, :email, :nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/gets_helper.rb
module GetsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bikes/index.html.haml
.bike
  -@bikes.each do |b|
    = link_to b.model, bike_path(b.id), class:"bike"
    -# b.title
    -# = link_to "詳細", "/bikes/#{@bikes.find(params[:id])}"
    

    

app/views/bikes/new.html.haml
.bikes
  .new
    .content
      .content__form
        = form_for @bike do |f|
          = render 'layouts/error', model: f.object
          .content__form__box
            .content__form__box__name
              = "ブランド名"
            = f.text_field :brand,class:"field"
          .content__form__box
            .content__form__box__name
              = "車種名　　"
            = f.text_field :model,class:"field"
          .content__form__box
            .content__form__box__name
              = "価格　　　"
            = f.text_field :price,class:"field"
          .content__form__box
            .content__form__box__name
              = "重さ　　　"
            = f.text_field :weight,class:"field"
          .content__form__image
            .content__form__image__name
              画像
            .content__form__image__main
              -# .content__form__image__main__box #ここから下5行はjsでアペンドされる要素
              -#   .content__form__image__main__box__pic
              -#   .content__form__image__main__box__btns
              -#     .content__form__image__main__box__btns__remove
              -#       = "削除"
              %label.content__form__image__main__label#label{for:"bike_images_attributes_0_src"}
                #image-box
                  = f.fields_for :images do |image|
                    .content__form__image__main__label__group{data:{index:image.index}}
                      = image.file_field :src,class:"file"
                    = "選択"
          .content__form__submit
            = f.submit :"登録する", class:"content__form__submit__btn"
      
        







  -# = form_for @bike do |f|
  -#   .content-n__info
  -#     車種を登録してください
  -#   .content-n__form
  -#     .content-n__form__box
  -#       .content-n__form__box__name
  -#         ブランド名
  -#         = f.text_field :brand_id
  -#     .content-n__form__box
  -#       .content-n__form__box__name
  -#         車種名
  -#         = f.text_field :model_id
  -#     .content-n__form__box
  -#       .content-n__form__box__name
  -#         画像
  -#         = f.text_field :image
  -#     .content-n__form__box
  -#       .content-n__form__box__name
  -#         価格
  -#         = f.text_field :price_id
  -#     .content-n__form__box
  -#       .content-n__form__box__name
  -#         重さ
  -#         = f.text_field :weight_id
  -#   = f.submit :"登録する", class:"content-n__submit"



    -# .content-n__form__box__name
    -#       ブランド名
    -#     = f.select :brand_id, [["あ","1"],["い","2"]], class:"content__form__box__btn"
    -#   .content-n__form__box
    -#     .content-n__form__box__name
    -#       車種名
    -#     = f.select :model_id, [["あ","1"],["い","2"]], class:"content__form__box__btn"
    -#   .content-n__form__box
    -#     .content-n__form__box__name
    -#       画像
    -#     = f.select :image, [["あ","1"],["い","2"]], class:"content__form__box__btn"
    -#   .content-n__form__box
    -#     .content-n__form__box__name
    -#       価格
    -#     = f.select :price_id, [["2","1"],["4","2"]], class:"content__form__box__btn"
    -#   .content-n__form__box
    -#     .content-n__form__box__name
    -#       重さ
    -#     = f.select :weight_id, [["1","1"],["2","2"]], class:"content__form__box__btn"
    -# = f.fields_for :brands do |i|
    -#       = i.text_field :name

app/views/bikes/search.html.haml
.bikes
  .search
    .contents
      - if (params[:search].present?)
        - @search.each do |s|
          .contents__content
            .contents__content__box
              .contents__content__box__list
                = "ブランド名:#{s.brand}"
              .contents__content__box__list
                = "車種:#{s.model}"
              .contents__content__box__list
                = "重さ:#{s.weight}"
              .contents__content__box__list
                = "価格:#{s.price}"
            .contents__content__right
              = link_to "この自転車の詳細に行く",bike_path(s.id),class:"contents__content__right__link"
      - else
        - @bikes.each do |b|
          .contents__content
            .contents__content__box
              .contents__content__box__list
                = "ブランド名:#{b.brand}"
              .contents__content__box__list
                = "車種:#{b.model}"
              .contents__content__box__list
                = "重さ:#{b.weight}"
              .contents__content__box__list
                = "価格:#{b.price}"
            .contents__content__right
              = link_to "この自転車の詳細に行く",bike_path(b.id),class:"contents__content__right__link"

app/views/bikes/show.html.haml
.bike
  .show
    .contents
      .contents__top
        .contents__top__detail
          .contents__top__detail__brand
            =  "ブランド名:#{@bike.brand}"
          .contents__top__detail__model
            = "車種名:#{@bike.model}"
          .contents__top__detail__weight
            = "重さ:#{@bike.weight}kg"
          .contents__top__detail__price
            = "価格:#{@bike.price}万"
        .contents__top__user
          .contents__top__user__header
            = "投稿者情報"
          - if @user.banned == nil && current_user.id != @user.id  #通報ボタンを投稿者以外かつ凍結していないユーザーしか押せない
            .contents__top__user__main
              -# - if current_user.id != @user.id #通報ボタンを投稿者以外しか押せない
              = "#{@user.nickname}さん"
            .contents__top__user__report{data:{index:@user.id}}
              = "通報"
          - elsif current_user.id == @user.id   #投稿者だった場合
            = "#{@user.nickname}さん"
          - else 
            = "凍結されたユーザーです"    #投稿者じゃないかつbannedカラムにidが入っている
      .contents__image
        .contents__image__box
          - @images.each do |i|
            = image_tag "#{i.src}",width:"100px",height:"100px"
      .contents__comment
      = "コメント"
      .contents__comment__box
        - @comments.each do |c|
          .contents__comment__box__list
            = c.text
      - if @user.banned == nil
        .contents__post
          = link_to "新規コメント", new_bike_comment_path(params[:id]),class:"comment"
      - else

app/views/bikes/top.html.haml
.bikes
  .top
    .content
      .content__top
        = form_tag(search_bikes_path, method: :get) do
          .content__top__count
            = "現在#{@bikes.count}台登録されています"
          .content__top__form
            = text_field_tag :search, "", {placeholder: "入力してください",class:"content__top__form__text"}
            = submit_tag '検索', {class:"content__top__form__submit"}
      .content__bottom
        .content__bottom__font
          ブランドから探す
        .content__bottom__list
          -@brands.each do |brand|
            .content__bottom__list__box
              .content__bottom__list__box__font
                = "ブランド名:"
                = link_to brand, search_bikes_path(brand),class:"content__bottom__list__box__font__link"
      .content__group
        .content__group__left
          = link_to "コミュニティー一覧はこちら", groups_path, class:"content__group__left__font"
          .content__group__left__list
            = "現在の動きがあったコミュニティー"
            - @groupIds.each do |g|
              .content__group__left__list__box#chat{data:{num:g}}
                = link_to @groups.find(g).name,group_chats_path(g),class:"content__group__left__list__box__name"

        

app/views/groups/index.html.haml
.groups
  .index
    .contents
      .contents__left
        -@groups.each do |g|
          .contents__left__content
            .contents__left__content__box
              .contents__left__content__box__left
                = link_to g.name,group_chats_path(g.id),class:"contents__left__content__box__left__name"
              .contents__left__content__box__right
      .contents__new
        = link_to "New",new_group_path,class:"contents__new__link"
        

        
          

app/views/groups/new.html.haml
-# 新規チャットグループ作成
.groups
  .new
    .contents
      .contents__form
        = form_for @group do |f|
          .contents__form__error-box
            = render 'layouts/error', model: f.object
          .contents__form__box
            .contents__form__box__left
              = f.text_field :name,placeholder:"新規コミュニティー名",class:"contents__form__box__left__group"
            .contents__form__box__right
              = f.submit "新規作成",class:"contents__form__box__right__submit"

app/views/users/new.html.haml
ユーザー新規登録画面

app/views/users/show.html.haml
.users
  .show
    .contents
      .contents__header
        .contents__header__mypage
          = "マイページ"
        .contents__header__index
          = "出品した商品一覧"
      .contents__main
        - @bikes.each do |b|
          .contents__main__box
            .contents__main__box__image
              = link_to bike_path(b.id) do
                = image_tag "#{Image.find_by(bike_id: b.id).src}",width:"100px",height:"100px"
            .contents__main__box__brand
              = b.brand
            .contents__main__box__name
              = b.model
      .contents__bottom